- src/components/Common/Footer.tsx
> [Feature] #6 - Footer 컴포넌트 추가

- src/components/Common/Input.tsx
- src/components/LoginPage/IdInput.tsx
- src/components/LoginPage/LoginBtn.tsx
- src/components/LoginPage/PasswordInput.tsx
- src/constants/regexList.ts
- src/pages/LoginPage.tsx
- tailwind.config.js
#17
1. Input 컴포넌트 추가 - 텍스트 포함 여부 및 에러 처리 포함
2. LoginPage onSubmit 함수 추가
> 17 feature loginpage enhance

- src/components/Common/Footer.tsx
- src/components/MyPage/UserProfile.tsx
- src/pages/MyPage.tsx
#14
- Footer css 수정
- UserProfile 컴포넌트 추가 (이미지는 임시로 넣어둠)
- MyPage에 UserProfile 컴포넌트 추가
> 14 feature userprofile component

- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/InfoContent.tsx
- src/components/MyPage/LikesContent.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/TabMenu.tsx
- src/components/MyPage/UserProfile.tsx
- src/pages/MyPage.tsx
#21
- tab 컴포넌트 생성
- mypage에 tab 추가
- post, comment, likes, info 컴포넌트 생성
> 21 feature tab component

- src/components/Common/Footer.tsx
- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/MyComment.tsx
- src/components/MyPage/TabMenu.tsx
- src/global.css
- src/router.tsx
#26
- Footer 위치 하단 고정
- 댓글 임시 아이템 추가
- MyComment 컴포넌트 추가
- TabMenu 변수명 수정
> 26 feature comment component

- .env
- .vscode/typescript.code-snippets
- .vscode/typescriptreact.code-snippets
- package-lock.json
- package.json
- src/components/Common/IdInput.tsx
- src/components/Common/Input.tsx
- src/components/Common/PasswordInput.tsx
- src/components/RegisterPage/ConfirmPasswordInput.tsx
- src/components/RegisterPage/Radio.tsx
- src/constants/groupList.ts
- src/customTypes/userInfo.ts
- src/pages/LoginPage.tsx
- src/pages/NameInput.tsx
- src/pages/RegisterPage.tsx
- src/services/login.ts
- src/services/register.ts
- tsconfig.app.json
#27
1. services 폴더 생성 -> login.ts, register.ts 추가
2. LoginPage, RegisterPage에서 해당 api들 적용 및 테스트 완료
3. api-req 스니펫 추가
https://github.com/user-attachments/assets/7091386a-6b24-4968-947a-db3e16a6f84c
> 27 feature login  register apis

- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/LikesContent.tsx
- src/components/MyPage/MyComment.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/TabMenu.tsx
- src/components/MyPage/UserProfile.tsx
- src/customTypes/commentInfo.ts
- src/pages/MyPage.tsx
#45
- 타입 정의를 외부 파일로 분리 (user, comment)
- postlistitem컴포넌트를 내 게시글과 좋아요에 불러옴
> 45 feature mypost component

- src/components/Common/Footer.tsx
> Feat: 로고 클릭 시 main으로

- src/components/MyPage/TabMenu.tsx
> Style: 좋아요 -> 스크랩으로 수정

- src/components/SearchPage/NoResult.tsx
> Feat: NoResult 컴포넌트 추가

- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderUserModal.tsx
> Feat: Header 로그인, 로그아웃 백엔드 연동

- src/components/MyPage/LikesContent.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/TabMenu.tsx
> 61 feature tabmenu component

- .env
- src/components/Common/HeaderUserModal.tsx
> fixed untracked files

- src/components/Common/Header.tsx
- src/components/Common/HeaderMenu.tsx
#7
* 모바일 헤더 사이드바(메뉴) 로그인 여부에 따라 적용한 UI
> Feat: 모바일 Header 햄버거 버튼  로그인 여부에 따른 UI

- src/components/MyPage/InfoContent.tsx
- src/components/MyPage/TabMenu.tsx
- src/components/MyPage/UserProfile.tsx
- src/pages/MyPage.tsx
#79 
- 임시 타입 삭제 및 UserInfo 타입 수정
- TabMenu 스타일 코드 수정
- getUserInfo api 연결
> 79 feature userprofile component

- package-lock.json
- package.json
- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/NoUserContent.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/TabMenu.tsx
- src/main.tsx
- tsconfig.json
#84
- CommentsContent 컴포넌트 api 연결
- NoUserContent 컴포넌트 스타일 수정
- TabMenu 컴포넌트 임시 댓글 데이터 삭제
- suspense 사용하니까 오류가 너무 많이 발생해서 일단 그냥 useQuery 사용했습니다
> 84 feature commentscontent api

- src/components/Common/Header.tsx
- src/components/Common/SearchBar.tsx
- src/components/Common/SearchFilter.tsx
- src/pages/SearchPage.tsx
#40
* URL 에서 검색 조건 받아와 검색 페이지 UI 구현했습니다.
> Feat: 검색 상세 페이지 UI

- src/components/RankPage/RankHeader.tsx
- src/components/RankPage/RankListItem.tsx
- src/components/RankPage/RankTable.tsx
- src/pages/RankPage.tsx
#36
* 유저랭킹 페이지 테이블 사이즈 수정했습니다.
> Style: 유저랭킹 테이블 사이즈 수정

- src/components/Common/Header.tsx
- src/components/Common/HeaderUserModal.tsx
#7
* 로그아웃 시 메인으로 이동
* 게시물, 유저랭킹 페이지에서 헤더 css 수정
> 7 feature header components

- src/components/RankPage/RankListItem.tsx
- src/components/RankPage/RankTable.tsx
- src/customTypes/rank.ts
- src/pages/RankPage.tsx
#36
* 리액트 쿼리로 호출했습니다. 확인 부탁드립니다!
> Feat: 유저랭킹 페이지 백엔드 연동

- src/components/Common/Footer.tsx
- src/components/Common/Input.tsx
- src/components/Common/NoContent.tsx
- src/components/Common/PasswordInput.tsx
- src/components/MyPage/CheckPassword.tsx
- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/InfoContent.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/ScrapContent.tsx
- src/components/MyPage/UserProfile.tsx
- src/pages/MyPage.tsx
- tailwind.config.js
#92 
- 자잘한 css 수정
- 비밀번호 input에 눈 아이콘
- footer max-w 적용
> 92 feature sub

- package-lock.json
- package.json
- vite.config.ts
#101 
백엔드와의 쿠키 전송을 위해 프론트엔드를 vite-plugin-mkcert를 이용하여 https로 실행되도록 하였습니다.
> 101 feature https

- src/customTypes/comment.ts
- src/customTypes/post.ts
> Fix: API Types

- package-lock.json
- package.json
- src/components/PostCreatePage/VersionContainer.tsx
- src/components/PostDetailPage/CommentContainer.tsx
- src/components/PostDetailPage/Feedback.tsx
- src/customTypes/post.ts
- src/customTypes/postCreate.ts
- src/hooks/useCreatePost.ts
- src/pages/PostCreatePage.tsx
- src/pages/PostDetailPage.tsx
- src/services/post/createPost.ts
- src/utils/postCreate/postFormReducer.ts
CreatePost 타입, 변수 명, 폼 제출 형식 수정
> Fix: CreatePost 타입, 변수 명, 폼 제출 형식 수정

- package-lock.json
- package.json
- src/components/Common/Input.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/ScrapContent.tsx
#98
- 비밀번호 눈 아이콘 상태 변경
- 주석 삭제 
- Scrap null 값 처리
- api 테스트 완료
> 98 feature mypage api test

- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/PostsContent.tsx
- src/services/comment/getMyComments.ts
- src/services/post/getMyPosts.ts
- src/services/user/getUserPosts.ts
Feat: getUserPosts
#106
1. 기존 getUserPosts, getUserComments 를 getMy로 바꾸었습니다.
2. 새로운 getUserPosts를 추가하였습니다. 특정 유저의 게시물을 조회할 수 있습니다.
> Fix: User -> My, Feat: getUserPosts

- src/components/Common/PasswordInput.tsx
- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/InfoContent.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/ScrapContent.tsx
- src/services/auth/updateUser.ts
#108 
- Post, Comment, Scrap 무한 스크롤
- Mypage 유저 정보 변수 optional
- 유저 정보 수정 정규표현식 추가
- Password 오류 처리
> 108 feature infinite scroll

- package-lock.json
- package.json
- src/components/PostDetailPage/CodeViewer.tsx
#113
- react-syntax-highlighter 라이브러리 적용
> 113 feature code highlighter

- src/components/Common/Input.tsx
- src/components/Common/Radio.tsx
- src/components/MyPage/CheckPassword.tsx
- src/components/MyPage/InfoContent.tsx
- src/components/MyPage/MyComment.tsx
#118
- 글자 크기 줄임
- InfoContent 변수명 수정
> 118 feature mypage style code

- src/components/Common/SearchBar.tsx
- src/components/Common/SearchFilter.tsx
- src/pages/SearchPage.tsx
- src/services/post/searchPosts.ts
#40
* 검색어 결과에 대한 검색 페이지 api 호출
* postlist item클릭 시 상세 페이지 이동 해야합니다.
> Feat: 검색 페이지api호출

- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderUserModal.tsx
#7
* 헤더 프로필 이모티콘을 이미지로 수정
* 모달 위치 수정
> Style: Header nav 로그인 프로필  수정

- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/NotificationCount.tsx
- src/components/Common/SearchBar.tsx
#121
- NotificationCount 컴포넌트 
- SearchBar css 수정
> 121 feature bell count

- src/components/Common/SearchFilter.tsx
> Style: 검색 초기화 버튼 css 수정

- src/pages/SearchPage.tsx
> Refactor: URL 가져오기 간소화

- src/pages/LoginPage.tsx
- src/pages/RegisterPage.tsx
#134
- 로그인, 회원가입 페이지에서 로고 클릭 시 메인으로 이동합니다
> Feat: Logo 클릭시 메인

- src/components/Common/PostItemSkeleton.tsx
- src/components/Common/PostList.tsx
- src/components/Common/PostListItem.tsx
- src/components/MainPage/MainSection.tsx
- src/components/MainPage/PopularPostListwrap.tsx
- src/components/MainPage/PopularPostSection.tsx
- src/components/MainPage/PostSectionSkeleton.tsx
- src/components/MainPage/RecentPostListWrap.tsx
- src/components/MainPage/RecentPostSection.tsx
- src/components/MainPage/SubBanner.tsx
- src/router.tsx
- src/services/post/getPosts.ts
#119 
1. RecentPostSection , PopularPostSection 컴포넌트 API연결
2. RecentPostSection , PopularPostSection 구성요소에 Link 추가
3. Router에 필요한 인기게시글 라우트 추가
4. PostSection , PostItem 로딩/에러 발생 시 스켈레톤 UI 컴포넌트 추가
5. RecentPostSection , PopularPostSection 로딩/에러 발생 시 스켈레톤 UI가 보이도록 변경
> 119 feature mainpage postsection api

- src/App.tsx
- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderNotificationModal.tsx
- src/customTypes/notification.ts
- src/services/notification/getMyNotifications.ts
> 138 feature notification

- src/pages/LoginPage.tsx
- src/pages/RegisterPage.tsx
- src/services/auth/login.ts
#146
백엔드에서 id를 userId로 바꾸어 이에 맞춰 로그인 회원가입 부분 수정
> Fix: id -> userId

- src/components/Common/Input.tsx
- src/components/Common/Radio.tsx
#140
- error 메시지, radio 반응형 적용
> Style: error message 번웅형 적용

- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderNotificationModal.tsx
- src/components/Common/HeaderUserModal.tsx
#7
* 알림 호출 리액트 쿼리로 변경
* 알림, 사용자 모달 창 max-w 안 넘도록 변경.
> Feat: 알림 호출 리액트 쿼리로 수정

- src/components/Common/PostList.tsx
- src/components/Common/PostListIcon.tsx
- src/components/Common/PostListItem.tsx
- src/components/MainPage/MainBanner.tsx
- src/components/MainPage/PopularPostSection.tsx
- src/components/MainPage/RecentPostSection.tsx
- src/customTypes/post.ts
- tailwind.config.js
#144 
- banner 반응형
- item 반응형
- title 줄바꿈 가능하게
- 높이 고정 -> 유동적으로
여기서 더 작아지면
유저 아이디 아래로
> 144 feature postlistitem

- src/router.tsx
- src/stores/userStore.ts
#151
PostCreatePage,MyPage,LoginPage,RegisterPage에 Protected Route 적용하였습니다.
> Feat: Protected Route 적용

- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderNotificationModal.tsx
#7
* 로그인 했을 때만 알림 리액트 쿼리 요청
* 알림 메시지 길어지면 말줄임표.
> Style: 로그인 헀을 때만  쿼리 요청

- src/services/notification/deleteNotification.ts
- src/services/notification/readAllNotifications.ts
- src/services/notification/readNotification.ts
> Feat: 알림 API 추가

- src/components/Common/Header.tsx
- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderNotificationModal.tsx
- src/components/Common/HeaderUserModal.tsx
- src/components/Common/SearchBar.tsx
- src/global.css
#156 
- header 반응형 수정 (모바일에서 로고 위치 완전 center)
- header 상단 고정
- footer를 header길이 조절해서 하단 고정
- 자잘한 style 코드 수정
> 156 feature header style

- package.json
#163 
package.json에 누락되어 있던 swiper를 추가했습니다.
> Fix:package.json에 swiper가 누락된 문제 수정

- package-lock.json
- package.json
- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderNotificationModal.tsx
- src/components/MyPage/UserProfile.tsx
- src/components/PostDetailPage/CommentList.tsx
- src/components/PostDetailPage/CommentWrite.tsx
- src/customTypes/boring-avatars.d.ts
- src/customTypes/notification.ts
- tsconfig.app.json
#160 
귀여운 아바타를 프로필 이미지로 적용했습니다!
> 160 feature boring avatars

- src/components/Common/HeaderNotificationModal.tsx
- src/customTypes/notification.ts
#166 
getMyNotifications API 응답을 백엔드에 맞춰 수정
> Fix: API 응답 수정

- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderMenu.tsx
- src/components/Common/HeaderNotificationModal.tsx
> Feat: 알림 리액트 쿼리

- src/components/Common/PostItemSkeleton.tsx
- src/components/MainPage/MainBannerSkeleton.tsx
- src/components/MainPage/MainSection.tsx
- src/components/MainPage/PostSectionSkeleton.tsx
- src/components/MainPage/SubBannerSkeleton.tsx
#170 
1. MainSection의 MainBanner가 렌더링 시 의도하지 않은 애니메이션이 들어가 있는 문제 수정
2. 스켈레톤 컴포넌트들이 기존의 UI와 크기가 일치하지 않는 문제 수정
> 170 bug mainsection banner

- src/components/MainPage/SubBanner.tsx
- src/components/MainPage/SubSection.tsx
#175 
SubSection의 텍스트 크기를 28에서 24로 줄였습니다.
> Style:SubSection 텍스트  크기 감소

- src/components/Common/CodeViewer.tsx
#177 
- CodeViewer border를 제거했습니다
> Style: CodeViewer border remove

- src/components/MyPage/CommentsContent.tsx
- src/customTypes/post.ts
- src/hooks/useInfinite.ts
#179 
useInfinite 훅을 생성하여 무한 스크롤 구현 간편하게 했습니다
```ts
const { data, error, fetchNextPage, hasNextPage, isFetchingNextPage, isLoading } =
useInfinite<CommonCommentResponseProps>({ key: "userComments", fetchFunc: getMyComments, limit: 10 });
```
> Feat: useInfinite

- src/components/PostDetailPage/CommentList.tsx
#182 
댓글 아바타 name 알맞게 수정하였습니다.
> Fix: 댓글 아바타 name 알맞게 수정

- src/components/Common/Header.tsx
- src/components/Common/SearchBar.tsx
- src/components/Common/SearchFilter.tsx
- src/stores/searchFiltersStore.ts
> Style: 검색어 필터 zustand로 관리

- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/ScrapContent.tsx
> Feat: infinite hook 적용

- src/components/Common/Header.tsx
> Style: nav 글씨 hover css 문제 수정

- vercel.json
#189 
vercel.json 추가하여 배포 환경에서 새로고침 시 오류를 방지하였습니다.
> Feat: vercel.json

- src/components/PostDetailPage/CommentInteraction.tsx
- src/hooks/useThumbComment.ts
#199
1. 댓글 추천 기능 구현
-옵티미스틱 업데이트를 적용해 UI에 바로 적용
> 199 feature postdetailpage comment recommand

- src/components/PostCreatePage/EditorContainer.tsx
#198 
- highlight 적용 완료 (stylecomponent 사용 부분은 이후 변경 예정)
> Style: 글 작성 시 코드 highlight 적용

- src/components/Common/CodeViewer.tsx
- src/components/PostCreatePage/EditorContainer.tsx
- src/components/PostDetailPage/CommentEditor.tsx
- src/components/PostDetailPage/CommentWrite.tsx
> Style: style-component 제거

- index.html
- public/favicon.svg
> Style: 파비콘 이미지

- src/components/Common/CodeViewer.tsx
- src/global.css
#206
- 에디터 font size, line height
> Style: 에디터 font-size 및 line-height  수정

- src/components/Common/SearchBar.tsx
- src/pages/SearchPage.tsx
> Feat: 필터만 선택해서 검색 가능

- src/components/MyPage/MyComment.tsx
#213
- MyComment Component의 Style Code를 수정했습니다
> Style: MyComment Component Style Code 수정

- src/components/RankPage/RankHeader.tsx
- src/components/RankPage/RankListItem.tsx
- src/components/RankPage/RankTable.tsx
- src/customTypes/rank.ts
- src/pages/RankPage.tsx
> Style: 유저랭킹 페이지 이름을 아이디로 변경

- src/components/Common/Footer.tsx
- src/components/Common/Header.tsx
- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderNotificationModal.tsx
- src/components/Common/HeaderUserModal.tsx
- tailwind.config.js
#216
- Header 반응형 처리 (모바일로 가기 전 어중간한 부분)
> 216 feature header

- src/components/Common/SearchBar.tsx
> Feat: 검색 페이지에서 검색어, 필터 초기화

- package-lock.json
- src/components/RankPage/RankListItem.tsx
- src/pages/RankPage.tsx
#219
- 모바일 모드에서 style code 변경
- 유저 ID 클릭 시 유저 페이지로
> 219 feature rankingpage style

- package-lock.json
- src/components/PostDetailPage/CommentEditDelete.tsx
- src/components/PostDetailPage/CommentEditor.tsx
- src/components/PostDetailPage/CommentList.tsx
- src/components/PostDetailPage/EditableCodeViewer.tsx
- src/hooks/useCommentUpdate.ts
- src/pages/PostDetailPage.tsx
#128
1. CodeEditor 수정
2. 댓글 수정 기능 구현
- EditableCodeViewer
> 128 feature postdetailpage comment update

- src/App.tsx
- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/PostList.tsx
- src/components/Common/PostListItem.tsx
- src/components/Common/ProtectedRoute.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/ScrapContent.tsx
- src/components/PostDetailPage/PostDetail.tsx
- src/customTypes/userInfo.ts
- src/pages/AdminPage.tsx
- src/pages/SearchPage.tsx
- src/router.tsx
- src/services/post/getHiddenPosts.ts
- src/services/report/reportPost.ts
#204
admin 페이지 추가 및 관리자가 게시글 수정 삭제 가능
> 204 feature admin

- src/components/PostDetailPage/CommentList.tsx
> Fix: 추천버튼 원위치

- src/components/MyPage/ScrapContent.tsx
> Fix: Type Bug 수정

- src/pages/RegisterPage.tsx
#230 
회원가입 request 타입 불일치로 role: "user" 추가
> Fix: register request props

- src/components/Common/HeaderNotificationModal.tsx
> Style: 알림 메시지 수정

- src/components/Common/Header.tsx
- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderMenu.tsx
- tailwind.config.js
#233
- 로그인 전 화면 반응형 처리 (768~1080)
- 로그인 후 화면도 약간 수정
> 233 feature header style

- src/components/Common/PostListItem.tsx
#234
- PostListItem 태그 넘어가는 부분 수
> Style: 태그 넘어가는 부분 수정

- src/components/Common/ActionBtn.tsx
- src/components/PostCreatePage/DetailContainer.tsx
- src/components/PostCreatePage/EditorContainer.tsx
- src/components/PostCreatePage/LanSelectBtn.tsx
- src/components/PostCreatePage/TitleContainer.tsx
- src/components/PostCreatePage/VersionContainer.tsx
- src/components/PostCreatePage/VersionCountBtn.tsx
- src/pages/PostCreatePage.tsx
- tailwind.config.js
> Style: PostCreatePage style code 수정

- src/components/Common/SearchBar.tsx
- src/components/Common/SearchFilter.tsx
> Style: Header tags

- src/components/Common/Footer.tsx
- src/global.css
- src/router.tsx
- tailwind.config.js
> Style: Footer 하단 고정 부분 수정

- public/favicon.svg
- src/components/RankPage/RankHeader.tsx
- src/components/RankPage/RankListItem.tsx
- src/components/RankPage/RankTable.tsx
#36
* 파비콘 스타일 수정
* 유저랭킹페이지 스타일 수정
> 36 feature rankpage

- src/global.css
> Style: global.css 수정

- src/components/RankPage/RankListItem.tsx
- src/pages/RankPage.tsx
> Style: 유저랭킹 스타일 수정

- src/components/MainPage/MainBanner.tsx
- src/components/MainPage/MainSection.tsx
- src/components/MainPage/PopularPostSection.tsx
- src/components/MainPage/RecentPostSection.tsx
- src/components/MainPage/SubBannerWrap.tsx
- src/components/MainPage/SubSection.tsx
- src/components/MainPage/swiper.d.ts
- src/global.css
#239 
1. MainSection 슬라이드 배너에 pagenation 버튼 , autoplay 속성 추가
2. SubSection 슬라이드 배너에 pagenation 버튼 , autoplay 속성 추가
3. SubSection padding 수정
> 239 feature mainpage

- src/components/Common/DeleteBtn.tsx
- src/components/Common/EditBtn.tsx
- src/components/PostDetailPage/CommentEditDelete.tsx
- src/components/PostDetailPage/CommentInteraction.tsx
- src/components/PostDetailPage/CommentList.tsx
- src/components/PostDetailPage/CommentWrite.tsx
- src/components/PostDetailPage/LanVersionTagList.tsx
- src/components/PostDetailPage/PostDetailHeader.tsx
- src/components/PostDetailPage/PostMetaList.tsx
> 251 feature detailpage

- src/components/Common/NoContent.tsx
- src/components/MyPage/InfoContent.tsx
- src/components/MyPage/TabMenu.tsx
- src/pages/MyPage.tsx
- tailwind.config.js
#249
마이페이지 NoContent, CheckPassword 디자인 수정
> 249 feature design mypage

- src/components/Common/Input.tsx
> Fix: defaultValue warning 수정

- src/components/Common/PostList.tsx
- src/components/PostPage/PostPageHeader.tsx
- src/components/PostPage/PostPageList.tsx
- src/components/PostPage/PostPageListSkeleton.tsx
- src/pages/PostPage.tsx
#235 
1. PostPage의 select 버튼을 toggle버튼으로 변경
2. PostPage 내 컴포넌트들의 모바일 환경 스타일 수정
> 235 feature postpage

- src/components/PostDetailPage/PostDetailInteraction.tsx
- src/hooks/usePostReport.ts
> Feat: PostDetailPage 신고 기능 구현

- src/components/Common/Loading.tsx
> Style: 로딩 컴포넌트 위치 조정

- src/pages/MyPage.tsx
> Style: p-4로 수정

- src/components/Common/Footer.tsx
> Style: p-4

- src/components/RankPage/RankListItem.tsx
- src/components/RankPage/RankTable.tsx
- src/pages/RankPage.tsx
> Style: 유저랭킹 디자인 개선

- src/components/RankPage/RankListItem.tsx
> Style: 유저랭킹 모바일 스타일 수정

- src/pages/SearchPage.tsx
> Style: 검색 페이지 패딩 수정

- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/ScrapContent.tsx
> Style: p태그 위치 이동

- src/components/Common/HeaderUserModal.tsx
- src/components/Common/ProtectedRoute.tsx
- src/router.tsx
> Feat: Route to AdminPage

- src/pages/PostCreatePage.tsx
> Style: p-4, py-12

- src/components/Common/HeaderNotificationModal.tsx
- src/components/Common/HeaderUserModal.tsx
> Style: 모달 위치 조정

- src/components/PostDetailPage/PostDetailEditDelete.tsx
- src/hooks/usePostUpdate.ts
- src/pages/PostUpdatePage.tsx
- src/router.tsx
> 130 feature postdetailpage update

- src/pages/PostDetailPage.tsx
> Style: 페이지 간격 수정

- src/components/Common/PostList.tsx
- src/components/MainPage/PopularPostListwrap.tsx
- src/components/MainPage/RecentPostListWrap.tsx
- src/components/MainPage/SubBanner.tsx
- src/components/MainPage/SubBannerDefault.tsx
- src/components/MainPage/SubSection.tsx
- src/components/PostPage/PostPageHeader.tsx
- src/components/PostPage/PostPageList.tsx
- src/pages/PostPage.tsx
#261 
1. 게시글 목록 정렬 버튼 위치 수정 
2. 게시글 목록 페이지 패딩 수정 
3. 게시글 목록 모바일환경 텍스트 크기 수정
4. 게시글 목록 모바일환경 정렬토 버튼 스타일 수정
> 261 feature postpage

- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/NotificationCount.tsx
- src/components/Common/SearchBar.tsx
> Style: 알림 스타일 수정

- src/components/PostPage/PostPageList.tsx
- src/pages/PostPage.tsx
#282 
PostPage의 padding을 수정했습니다.
> 282 feature postpage style

- package.json
- src/pages/LoginPage.tsx
- src/pages/RegisterPage.tsx
> 284 feature design login register

- src/pages/PostUpdatePage.tsx
> Style: 게시물 수정 페이지 간격 수정

- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/InfoContent.tsx
- src/components/MyPage/MyComment.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/ScrapContent.tsx
> Style: css 코드 수정

- src/components/MyPage/InfoContent.tsx
> Style: calc 수정

- src/components/Common/SearchBar.tsx
> Style: 중복 md 제거

- src/components/Common/SearchBar.tsx
- src/components/Common/SearchFilter.tsx
> Style: 함수명 변경

- src/components/Common/HeaderNotificationModal.tsx
- src/customTypes/notification.ts
#300 
notification.post._id가 존재하지 않는 경우 예외처리를 통해 삭제된 게시물에 대한 알림 정상 동작하도록 함
> Fix: 삭제된 게시물에 대한 알림

- src/components/Common/CodeViewer.tsx
- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/ScrapContent.tsx
- src/pages/PostCreatePage.tsx
- src/pages/PostDetailPage.tsx
- src/pages/PostUpdatePage.tsx
> 304 bug codeviewer code block

- package-lock.json
- package.json
- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/InfoContent.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/ScrapContent.tsx
- src/components/MyPage/TabMenu.tsx
- src/components/PostDetailPage/CommentEditDelete.tsx
- src/components/PostDetailPage/CommentList.tsx
- src/components/PostDetailPage/CommentWrite.tsx
- src/components/PostDetailPage/PostDetailEditDelete.tsx
- src/hooks/useCreateComment.ts
- src/hooks/useInfiniteComment.ts
- src/pages/MyPage.tsx
- src/pages/PostCreatePage.tsx
- src/pages/PostDetailPage.tsx
- src/pages/PostUpdatePage.tsx
- src/services/comment/getComments.ts
- src/services/post/deletePost.ts
- src/services/post/getPostDetail.ts
- src/utils/postCreate/postFormReducer.ts
- src/utils/sweetAlert/alerts.ts
- src/utils/sweetAlert/config.ts
#288
1. : 게시글 상세, 작성, 수정 및 댓글 관련 알림 수정
2. 마이 페이지 에러페이지 연동 및 알림 수정
3. 무한 스크롤 로딩 이펙트 설정
4. 게시물 로딩 이펙트 설정
> 288 [refactor] alert 적용 및 고칠 사항 수정

- src/components/Common/EditBtn.tsx
- src/components/PostDetailPage/PostDetail.tsx
- src/hooks/useCreatePost.ts
- src/pages/PostDetailPage.tsx
- src/pages/PostUpdatePage.tsx
> Fix: 게시물 업데이트 페이지 오류 수정

- src/components/PostDetailPage/PostDetail.tsx
> Fix: 알림 오류 수정

- src/components/MainPage/PopularPostSection.tsx
- src/components/MainPage/RecentPostSection.tsx
- src/components/PostPage/PostPageList.tsx
- src/pages/PostPage.tsx
- src/router.tsx
#310 
1. 인기/최신게시글 더보기 클릭 시 url대신 state를 통해 분기처리하도록 변경
> Refactor:인기/최신게시글 더보기 클릭 시 url대신 state를 통해 분기처리하도록 변경

- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderNotificationModal.tsx
- src/hooks/useModal.ts
#7
*  모바일 알림 스크롤 수정
* 헤더 로그인 시 is loading... 안 보이게 수정
> Style: 모바일 알림 스크롤 수정

- src/components/Common/HeaderNotificationModal.tsx
> Style: 모바일 알림창 스크롤바 중복 제한

- src/components/Common/Header.tsx
- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderMenu.tsx
- src/components/Common/HeaderUserModal.tsx
- src/global.css
- src/services/auth/logout.ts
- tailwind.config.js
> Style: HeaderMenu 디자인

- src/components/Common/ActionBtn.tsx
- src/components/PostDetailPage/CommentList.tsx
- src/components/PostDetailPage/CommentWrite.tsx
- src/components/PostDetailPage/EditableCodeViewer.tsx
- src/components/PostDetailPage/PostDetailActBtn.tsx
- src/components/PostDetailPage/PostDetailInteraction.tsx
- src/components/PostDetailPage/index.ts
- src/customTypes/comment.ts
- src/hooks/useCommentUpdate.ts
- src/hooks/useCreateComment.ts
- src/utils/sweetAlert/alerts.ts
- src/utils/sweetAlert/config.ts
#306
1. 옵티미스틱 업데이트 시 누락된 댓글 데이터 연동
2. 댓글 수정 버튼 디자인 변경 및 컴포넌트 화
3. 신고 기능 디자인 변경
> 306 bug comment

- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/HeaderNotificationModal.tsx
- src/hooks/useNotificationMutations.ts
- src/hooks/useNotifications.ts
#315
*알림 React Query  Custom hook
> Feat: 알림 React Query  Custom hook

- src/components/Common/Header.tsx
- src/components/Common/HeaderLoginMenu.tsx
> Style : 모바일 헤더 위치 조정

- src/components/Common/SearchBar.tsx
> Fix: search KeyPress으로 변경

- src/components/Common/DeleteBtn.tsx
- src/components/Common/EditBtn.tsx
- src/components/PostDetailPage/CommentInteraction.tsx
- src/components/PostDetailPage/CommentList.tsx
- src/components/PostDetailPage/PostDetailEditDelete.tsx
- src/components/PostDetailPage/PostDetailHeader.tsx
- src/components/PostDetailPage/PostDetailInteraction.tsx
- src/components/PostDetailPage/PostMetaList.tsx
> Refactor: 수정된 게시물 수정됨 표시 및 스타일 수정

- src/components/PostCreatePage/LanSelectBtn.tsx
- src/pages/PostCreatePage.tsx
1. selct 포커스 시 링 삭제
2. 제목 글자수 100으로 증가
> Fix: select 포커스 시 링 제거

- src/components/MainPage/SubBannerSkeleton.tsx
- src/components/MainPage/SubSection.tsx
#325 
1. 에러메시지가 [답변을 기다리는 게시글이 존재하지 않습니다] 일 경우 게시글 작성 배너 표시
2. 그 외 에러는 대체 컴포넌트 내에 에러메시지를 표시
> Feat:SubSection 답변을 기다리는 게시글이 없을 경우 게시글 작성 배너 표시

- src/components/Common/SearchBar.tsx
- src/components/MyPage/CheckPassword.tsx
- src/components/MyPage/InfoContent.tsx
- src/components/PostDetailPage/CommentInteraction.tsx
- src/components/PostDetailPage/CommentWrite.tsx
- src/components/PostDetailPage/PostDetailInteraction.tsx
- src/hooks/usePostLikeScrap.ts
- src/pages/LoginPage.tsx
- src/pages/RegisterPage.tsx
- src/pages/index.tsx
- src/router.tsx
- src/services/axiosInstance.ts
> 323 feature sweet alert

- src/components/Common/HeaderLoginMenu.tsx
- src/components/Common/Loading.tsx
- src/components/MyPage/CommentsContent.tsx
- src/components/MyPage/InfoContent.tsx
- src/components/MyPage/PostsContent.tsx
- src/components/MyPage/ScrapContent.tsx
- src/components/PostDetailPage/CommentList.tsx
- src/pages/AdminPage.tsx
- src/pages/MyPage.tsx
- src/pages/PostCreatePage.tsx
- src/pages/PostDetailPage.tsx
- src/pages/PostUpdatePage.tsx
- src/pages/RankPage.tsx
- src/pages/SearchPage.tsx
#329 
- 로딩 컴포넌트 쓰는 페이지 전부 스타일 코드 수정
> Style: Loading 쓰는 페이지들 전부 수정

- src/pages/AdminPage.tsx
> Style: AdminPage 패딩 적용
